bnb_api_key = 'gpK0jBSVjE7foKq6f4XWhu62noj3GWv90Swv8CKsFDsBxTodtvs5Sd2pGy1NZblB'
bnb_api_secret = 'Zd28WyeRww6maVfQFYFcZO2W7XFGBZ4FNdYBhLt9Jtsl89SKgCCS9CNxBSdQNDGP'
app_secret_key = b'gnkjJKJIEigkibjgjOPJTlpIorkgopfklkJfkgopdklgkLKldgo'